# Generated by Django 6.0.2 on 2026-02-23 02:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('BANK', 'Bank Account'), ('CREDIT_CARD', 'Credit Card')], max_length=20)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('institution', models.CharField(blank=True, max_length=255, null=True)),
                ('last4', models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.MaxLengthValidator(4)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
