# Generated by Django 6.0.2 on 2026-02-23 02:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionImportSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('delimiter', models.CharField(default=',', max_length=5)),
                ('has_header', models.BooleanField(default=True)),
                ('date_column', models.CharField(max_length=255)),
                ('description_column', models.CharField(max_length=255)),
                ('amount_column', models.CharField(max_length=255)),
                ('category_column', models.CharField(blank=True, max_length=255, null=True)),
                ('date_format', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
