# Generated by Django 6.0.2 on 2026-02-23 16:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_transactionimportsource'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('DRY_RUN', 'Dry Run'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='DRY_RUN', max_length=20)),
                ('total_rows', models.IntegerField(default=0)),
                ('imported_rows', models.IntegerField(default=0)),
                ('forced_duplicate_count', models.IntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.account')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.transactionimportsource')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RawTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('txn_at_utc', models.DateTimeField()),
                ('description', models.TextField()),
                ('amount', models.BigIntegerField()),
                ('category_raw', models.TextField(blank=True, null=True)),
                ('fingerprint_hash', models.CharField(db_index=True, max_length=64)),
                ('is_forced_duplicate', models.BooleanField(default=False)),
                ('force_reason', models.TextField(blank=True, null=True)),
                ('forced_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.account')),
                ('forced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.importbatch')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.transactionimportsource')),
            ],
        ),
    ]
